## Demonstrate Connectivity Widget 

In [1]:
# from tvbwidgets.api import ConnectivityWidgetReact
# from tvb.datatypes.connectivity import Connectivity

# connectivity = Connectivity.from_file() # defaults to connectivy_76.zip


# wid = ConnectivityWidgetReact(connectivity=connectivity)
# wid

In [2]:
from tvbwidgets.api import ConnectivityWidget
from tvb.datatypes.connectivity import Connectivity
import pyvista as pv
import numpy as np
pv.set_jupyter_backend('pythreejs')

conn = Connectivity.from_file() # defaults to connectivy_76.zip
conn.configure()

wid = ConnectivityWidget(conn)

display(wid)

14-09-2023 04:28:58 - DEBUG - tvbwidgets - Package is not fully installed
14-09-2023 04:28:58 - DEBUG - tvbwidgets - Version read from the internal package.json file
14-09-2023 04:28:58 - INFO - tvbwidgets - Version: 1.5.0
2023-09-14 16:29:04,296 - INFO - tvb.storage.h5.encryption.data_encryption_handler - Cannot import syncrypto library.
14-09-2023 04:29:04 - INFO - tvbwidgets.core.pse.parameters - ImportError: Dask dependency is not included, so this functionality won't be available
2023-09-14 16:29:04,405 - WARNING - tvb.basic.readers - File 'hemispheres' not found in ZIP.
connectivity.weights:  [[2. 2. 0. ... 0. 0. 0.]
 [3. 2. 0. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 2. 0.]
 [0. 0. 0. ... 3. 2. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
edge_indices:  (array([ 0,  0,  0, ..., 74, 74, 74], dtype=int64), array([ 0,  1,  3, ..., 72, 73, 74], dtype=int64))
edges:  [(0, 0), (0, 1), (0, 3), (0, 6), (0, 10), (0, 11), (0, 18), (0, 20), (0, 21), (0, 24), (0, 30), (0, 33), (0, 34)

ConnectivityWidget(children=(VBox(children=(HTML(value='<h1>Connectivity - 76</h1>'), HBox(children=(Checkbox(…

In [3]:
# replace None in the method below with the gid of the connectivity you wish to export
# if no gid is provided it will export the connectivity currently viewed

new_connectivity = wid.get_connectivity(gid=None)  
new_connectivity