In [1]:
from tvb.datatypes.connectivity import Connectivity
from tvbwidgets.ui.connectivity_react.connectvity_widget_new import ConnectivityWidget

conn = Connectivity.from_file()
conn.configure()

w = ConnectivityWidget(conn)
display(w)

22-03-2026 11:56:24 - INFO - tvbwidgets - Version: 2.3.2
2026-03-22 11:56:24,727 - WARNING - tvb.basic.readers - File 'hemispheres' not found in ZIP.
ConnectivityWidget ready — 76 regions.


In [2]:
import numpy as np

w = conn.weights
t = conn.tract_lengths

# Only look at connected pairs
mask = w != 0
connected_tracts = t[mask]

print("Connected tract lengths (mm):")
print(f"  Min:    {connected_tracts.min():.2f}")
print(f"  Max:    {connected_tracts.max():.2f}")
print(f"  Mean:   {connected_tracts.mean():.2f}")
print(f"  Median: {np.median(connected_tracts):.2f}")

# Distribution
percentiles = [10, 25, 50, 75, 90]
for p in percentiles:
    print(f"  {p}th percentile: {np.percentile(connected_tracts, p):.2f} mm")

Connected tract lengths (mm):
  Min:    0.00
  Max:    138.45
  Mean:   57.01
  Median: 55.86
  10th percentile: 25.36 mm
  25th percentile: 37.92 mm
  50th percentile: 55.86 mm
  75th percentile: 75.36 mm
  90th percentile: 93.04 mm


In [2]:
import numpy as np

# Check tract_lengths matrix
tl = conn.tract_lengths
print("tract_lengths shape:", tl.shape)
print("Non-zero per region:", np.count_nonzero(tl, axis=1))
print("Zero entries:", np.sum(tl == 0))
print("Min value:", tl.min())
print("Max value:", tl.max())
print("Sample values (first 5x5):")
print(tl[:5, :5])

tract_lengths shape: (76, 76)
Non-zero per region: [73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73
 73 73 73 73 73 73 73 73 73 73 73 73 73  0 73 73 73 73 73 73 73 73 73 73
 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73 73
 73 73 73  0]
Zero entries: 374
Min value: 0.0
Max value: 153.48574
Sample values (first 5x5):
[[ 0.       20.330072 32.876029 45.482256 43.214474]
 [20.330072  0.       46.623042 65.051623 56.046734]
 [32.876029 46.623042  0.       50.377749 55.580848]
 [45.482256 65.051623 50.377749  0.       42.488013]
 [43.214474 56.046734 55.580848 42.488013  0.      ]]


In [3]:
# Verify this theory
weights_nonzero = conn.weights != 0
tracts_nonzero  = conn.tract_lengths != 0

print("Regions with weight connection but no tract:", np.sum(weights_nonzero & ~tracts_nonzero))
print("Regions with tract but no weight connection:", np.sum(tracts_nonzero & ~weights_nonzero))

Regions with weight connection but no tract: 66
Regions with tract but no weight connection: 3908
